In [ ]:
from google.colab import userdata

try:
    HF_TOKEN = userdata.get('HF_TOKEN')
    print('✅ HF_TOKEN loaded successfully')
except Exception:
    HF_TOKEN = None
    print('⚠️ HF_TOKEN not set — OK for public models, but needed to push to Hub')

REPO_ID = 'Hemachandiran/medqa-deepseek'

⚠️ HF_TOKEN not set — OK for public models, but needed to push to Hub

In [ ]:
!pip install -q \
    transformers \
    peft \
    trl \
    accelerate \
    datasets \
    huggingface_hub

print('Done')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 697.4/697.4 kB 22.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 32.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 17.7 MB/s eta 0:00:00
Done

In [ ]:

import os
os.kill(os.getpid(), 9)

In [ ]:
from huggingface_hub import login
login(token=HF_TOKEN)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
# Cell 2 — Mount Drive + verify GPU
from google.colab import drive
drive.mount('/content/drive')

import torch
assert torch.cuda.is_available(), 'No GPU found! Change runtime to T4'
print(f'GPU  : {torch.cuda.get_device_name(0)}')
print(f'VRAM : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

Mounted at /content/drive
GPU  : Tesla T4
VRAM : 15.6 GB

In [ ]:
import torch, transformers, accelerate, peft, trl

print(f'torch        : {torch.__version__}')
print(f'transformers : {transformers.__version__}')
print(f'accelerate   : {accelerate.__version__}')
print(f'peft         : {peft.__version__}')
print(f'trl          : {trl.__version__}')
print(f'CUDA available: {torch.cuda.is_available()}')

torch        : 2.10.0+cu128
transformers : 5.0.0
accelerate   : 1.13.0
peft         : 0.18.1
trl          : 1.2.0
CUDA available: True

In [ ]:
from datasets import load_dataset

dataset = load_dataset('json', data_files={
    'train':      '/content/drive/MyDrive/medqa_processed/train.jsonl',
    'validation': '/content/drive/MyDrive/medqa_processed/val.jsonl'
})
print(dataset)

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 9160
    })
    validation: Dataset({
        features: ['text'],
        num_rows: 1018
    })
})

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

MODEL_ID = 'deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B'

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tokenizer.pad_token    = tokenizer.eos_token
tokenizer.padding_side = 'right'

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype=torch.float16,           # ✅ Fixed: was torch_dtype (deprecated)
    device_map='auto',
    trust_remote_code=True,

)

model.gradient_checkpointing_enable()
model.enable_input_require_grads()

print('Model loaded!')
print(f'VRAM used : {torch.cuda.memory_allocated() / 1e9:.2f} GB')
print(f'VRAM free : {(torch.cuda.get_device_properties(0).total_memory - torch.cuda.memory_allocated()) / 1e9:.2f} GB')

config.json:   0%|          | 0.00/679 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/3.55G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

Model loaded!
VRAM used : 3.55 GB
VRAM free : 12.08 GB

In [ ]:
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=[
        'q_proj', 'k_proj',
        'v_proj', 'o_proj',
        'gate_proj', 'up_proj', 'down_proj'
    ],
    lora_dropout=0.05,
    bias='none',
    task_type='CAUSAL_LM',
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 18,464,768 || all params: 1,795,552,768 || trainable%: 1.0284

In [ ]:
for name, param in model.named_parameters():
    if param.requires_grad:
        print(name)
        break

base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight

In [ ]:
from trl import SFTTrainer, SFTConfig

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset['train'],
    eval_dataset=dataset['validation'],
    processing_class=tokenizer,
    args=SFTConfig(
        output_dir='./checkpoints',
        num_train_epochs=2,
        per_device_train_batch_size=2,
        per_device_eval_batch_size=2,
        gradient_accumulation_steps=8,
        warmup_steps=50,
        learning_rate=1e-4,
        fp16=True,
        logging_steps=50,
        eval_strategy='steps',
        eval_steps=200,
        save_strategy='steps',
        save_steps=200,
        load_best_model_at_end=True,
        lr_scheduler_type="cosine",
        report_to='none',
        max_length=512,
        dataset_text_field='text',
        packing=False,
    ),
)

trainer.train()

Adding EOS to train dataset:   0%|          | 0/9160 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/9160 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/1018 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/1018 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': 151646, 'pad_token_id': 151643}.

TrainOutput(global_step=1146, training_loss=1.5745007646437508, metrics={'train_runtime': 5959.5701, 'train_samples_per_second': 3.074, 'train_steps_per_second': 0.192, 'total_flos': 4.613700929203814e+16, 'train_loss': 1.5745007646437508})

In [ ]:
model.save_pretrained("/content/drive/MyDrive/deepseek-medqa-lora")
tokenizer.save_pretrained("/content/drive/MyDrive/deepseek-medqa-lora")

('/content/drive/MyDrive/deepseek-medqa-lora/tokenizer_config.json',
 '/content/drive/MyDrive/deepseek-medqa-lora/chat_template.jinja',
 '/content/drive/MyDrive/deepseek-medqa-lora/tokenizer.json')

In [ ]:
model.save_pretrained('./final_model')
tokenizer.save_pretrained('./final_model')
print('✅ Model saved locally')

✅ Model saved locally

In [ ]:
from huggingface_hub import login
login(token="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")  # Make sure HF_TOKEN is set in Colab Secrets

model.push_to_hub(REPO_ID)
tokenizer.push_to_hub(REPO_ID)
print(f'✅ Model pushed to https://huggingface.co/{REPO_ID}')

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          | 45.7kB / 73.9MB

README.md: 0.00B [00:00, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mplqp_7v9r/tokenizer.json:  97%|#########7| 11.1MB / 11.4MB

✅ Model pushed to https://huggingface.co/Hemachandiran/medqa-deepseek

In [ ]:
questions = [
    "A 7-year-old child presents with high fever, stiff neck, and photophobia. What is the most likely diagnosis?",
    "A patient presents with polyuria, polydipsia, and weight loss. Blood glucose is 320 mg/dL. What is the diagnosis?",
    "A 60-year-old woman presents with progressive memory loss and confusion. MRI shows cortical atrophy. What is the diagnosis?",
]

model.eval()

for i, question in enumerate(questions):
    input_text = f"### Question:\n{question}\n\n### Answer:"
    inputs = tokenizer(input_text, return_tensors='pt').to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            temperature=0.7,
            do_sample=True,
            top_p=0.9,
            repetition_penalty=1.1,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Print only the answer part
    answer = response.split('### Answer:')[-1].strip()
    print(f"Q{i+1}: {question}")
    print(f"A{i+1}: {answer}")
    print("-" * 60)

Q1: A 7-year-old child presents with high fever, stiff neck, and photophobia. What is the most likely diagnosis?
A1: Myelosuppression

The answer is Myelosuppression.
------------------------------------------------------------
Q2: A patient presents with polyuria, polydipsia, and weight loss. Blood glucose is 320 mg/dL. What is the diagnosis?
A2: Type II diabetes mellitus

### Explanation:
Type II diabetes mellitus involves the inability of insulin to bind to glucose molecules in the blood. The glucose transporters are impaired so that glucose enters the bloodstream through capillary walls, not via diffusion. This results in a high concentration of glucose in the blood and low concentrations in tissues.
------------------------------------------------------------
Q3: A 60-year-old woman presents with progressive memory loss and confusion. MRI shows cortical atrophy. What is the diagnosis?
A3: Alcoholic Slice

The answer is Alcoholic Slice.

Explanation: The patient's memory loss and confusion are most likely caused by a brain disorder that affects memory and attention. A 60-year-old woman is presented to an physician for progressive memory loss, cognitive impairment, and confusion. She was diagnosed with Alzheimer’s disease 12 years ago. She has a history of alcohol use and is currently on methadone therapy. Her past medical history is significant for a 3-month history of fatigue. She reports a 70 kg (154 lb) weight loss over the past month. Her vital signs include: blood pressure 140/90 mm Hg, pulse 82/min, respiratory rate 16/min, and temperature 36.5°C (97.7°F). On physical examination, she appears pale and incoherent. The neurological exam demonstrates bilateral motor deficits and a 3- to 4-point memory deficit. She also
------------------------------------------------------------

In [ ]:
import torch

model.eval()

def ask(question):
    input_text = (
        "<|system|>\n"
        "You are a medical AI assistant trained on clinical questions. "
        "Answer clearly, accurately, and concisely.\n\n"
        f"<|user|>\n{question}\n\n"
        "<|assistant|>\n"
    )

    inputs = tokenizer(input_text, return_tensors='pt').to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=150,
            temperature=0.1,
            do_sample=True,
            top_p=0.85,
            repetition_penalty=1.3,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    answer = response.split('<|assistant|>')[-1].strip()
    return answer

# ✅ Test questions
questions = [
    "A 7-year-old child presents with high fever, stiff neck, and photophobia. What is the most likely diagnosis?",
    "A patient presents with polyuria, polydipsia, and weight loss. Blood glucose is 320 mg/dL. What is the diagnosis?",
    "A 60-year-old woman presents with progressive memory loss and confusion. MRI shows cortical atrophy. What is the diagnosis?",
]

for i, q in enumerate(questions):
    print(f"Q{i+1}: {q}")
    print(f"A{i+1}: {ask(q)}")
    print("-" * 60)

Q1: A 7-year-old child presents with high fever, stiff neck, and photophobia. What is the most likely diagnosis?
A1: The answer is Chlamydia trachomatis infection.
------------------------------------------------------------
Q2: A patient presents with polyuria, polydipsia, and weight loss. Blood glucose is 320 mg/dL. What is the diagnosis?
A2: The answer is Type II diabetes mellitus (TIDM).
------------------------------------------------------------
Q3: A 60-year-old woman presents with progressive memory loss and confusion. MRI shows cortical atrophy. What is the diagnosis?
A3: The answer is Alzheimer's disease.
------------------------------------------------------------

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

MODEL_ID   = 'deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B'
CHECKPOINT = './checkpoints/checkpoint-1000'   # ✅ exact path

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tokenizer.pad_token    = tokenizer.eos_token
tokenizer.padding_side = 'right'

# Load base model
base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype=torch.float16,
    device_map='auto',
    trust_remote_code=True,
)

# ✅ Load your already trained LoRA weights
model = PeftModel.from_pretrained(base_model, CHECKPOINT)
model.gradient_checkpointing_enable()
model.enable_input_require_grads()

print('✅ Resumed from checkpoint-1000!')
print(f'VRAM used : {torch.cuda.memory_allocated() / 1e9:.2f} GB')
print(f'VRAM free : {(torch.cuda.get_device_properties(0).total_memory - torch.cuda.memory_allocated()) / 1e9:.2f} GB')

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

✅ Resumed from checkpoint-1000!
VRAM used : 10.98 GB
VRAM free : 4.65 GB

In [ ]:
import os

# ✅ Remove scaler.pt files too
for ckpt in ['./checkpoints/checkpoint-1000',
             './checkpoints/checkpoint-800',
             './checkpoints/checkpoint-600',
             './checkpoints/checkpoint-400',
             './checkpoints/checkpoint-200']:
    for f in ['optimizer.pt', 'scaler.pt', 'scheduler.pt', 'rng_state.pth']:
        path = os.path.join(ckpt, f)
        if os.path.exists(path):
            os.remove(path)
            print(f'🗑️ Removed {f} from {ckpt}')

print('✅ Done cleaning')

🗑️ Removed scaler.pt from ./checkpoints/checkpoint-1000
🗑️ Removed scheduler.pt from ./checkpoints/checkpoint-1000
🗑️ Removed rng_state.pth from ./checkpoints/checkpoint-1000
🗑️ Removed scaler.pt from ./checkpoints/checkpoint-800
🗑️ Removed scheduler.pt from ./checkpoints/checkpoint-800
🗑️ Removed rng_state.pth from ./checkpoints/checkpoint-800
🗑️ Removed scaler.pt from ./checkpoints/checkpoint-600
🗑️ Removed scheduler.pt from ./checkpoints/checkpoint-600
🗑️ Removed rng_state.pth from ./checkpoints/checkpoint-600
🗑️ Removed scaler.pt from ./checkpoints/checkpoint-400
🗑️ Removed scheduler.pt from ./checkpoints/checkpoint-400
🗑️ Removed rng_state.pth from ./checkpoints/checkpoint-400
🗑️ Removed scaler.pt from ./checkpoints/checkpoint-200
🗑️ Removed scheduler.pt from ./checkpoints/checkpoint-200
🗑️ Removed rng_state.pth from ./checkpoints/checkpoint-200
✅ Done cleaning

In [ ]:
from trl import SFTTrainer, SFTConfig

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset['train'],
    eval_dataset=dataset['validation'],
    processing_class=tokenizer,
    args=SFTConfig(
        output_dir='./checkpoints_v2',
        num_train_epochs=3,
        per_device_train_batch_size=2,
        per_device_eval_batch_size=2,
        gradient_accumulation_steps=8,
        warmup_steps=100,
        learning_rate=2e-5,
        fp16=False,                    # ✅ disabled
        bf16=True,                     # ✅ use bf16 instead
        logging_steps=50,
        eval_strategy='steps',
        eval_steps=200,
        save_strategy='steps',
        save_steps=200,
        load_best_model_at_end=True,
        lr_scheduler_type="cosine",
        report_to='none',
        max_length=512,
        dataset_text_field='text',
        packing=False,
    ),
)

trainer.train()

KeyboardInterrupt:

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

MODEL_ID   = 'deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B'
CHECKPOINT = './checkpoints/checkpoint-1000'

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tokenizer.pad_token    = tokenizer.eos_token
tokenizer.padding_side = 'right'

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype=torch.float16,
    device_map='auto',
    trust_remote_code=True,
)

model = PeftModel.from_pretrained(base_model, CHECKPOINT)

# ✅ Removed gradient_checkpointing_enable() — was causing CheckpointError
# ✅ Removed enable_input_require_grads()

print('✅ Model loaded from checkpoint-1000!')
print(f'VRAM used : {torch.cuda.memory_allocated() / 1e9:.2f} GB')
print(f'VRAM free : {(torch.cuda.get_device_properties(0).total_memory - torch.cuda.memory_allocated()) / 1e9:.2f} GB')

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

✅ Model loaded from checkpoint-1000!
VRAM used : 7.36 GB
VRAM free : 8.27 GB

In [ ]:
from trl import SFTTrainer, SFTConfig

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset['train'],
    eval_dataset=dataset['validation'],
    processing_class=tokenizer,
    args=SFTConfig(
        output_dir='./checkpoints_v3',
        num_train_epochs=3,
        per_device_train_batch_size=4,     # ✅ increased from 2
        per_device_eval_batch_size=4,      # ✅ increased from 2
        gradient_accumulation_steps=4,     # ✅ reduced from 8
        warmup_steps=50,                   # ✅ reduced from 100
        learning_rate=5e-5,               # ✅ increased from 2e-5
        fp16=False,
        bf16=True,
        logging_steps=50,
        eval_strategy='steps',
        eval_steps=100,                    # ✅ evaluate more frequently
        save_strategy='steps',
        save_steps=100,
        load_best_model_at_end=True,
        lr_scheduler_type="cosine",
        report_to='none',
        max_length=512,
        dataset_text_field='text',
        packing=False,
    ),
)

trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': 151646, 'pad_token_id': 151643}.

KeyboardInterrupt:

In [ ]:
import torch

model.eval()

def generate_answer(question):
    prompt = (
        "<|system|>\n"
        "You are a medical AI assistant trained on clinical questions. "
        "Answer clearly, accurately, and concisely.\n\n"
        f"<|user|>\n{question}\n\n"
        "<|assistant|>\n"
    )
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    input_length = inputs["input_ids"].shape[1]

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=150,
            temperature=0.1,
            top_p=0.85,
            do_sample=True,
            repetition_penalty=1.3,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    new_tokens = outputs[0][input_length:]
    return tokenizer.decode(new_tokens, skip_special_tokens=True).strip()


# ✅ Detailed questions matching training data style
test_cases = [
    (
        "A 21-year-old college student is brought to the emergency department with a 10-hour history of increasing headache, stiff neck, and sensitivity to light. Temperature is 39.5°C, heart rate is 110/min. What is the most likely diagnosis?",
        "Meningitis"
    ),
    (
        "A 45-year-old man presents with polyuria, polydipsia, and a 10 kg weight loss over 2 months. His fasting blood glucose is 320 mg/dL and HbA1c is 11%. What is the diagnosis?",
        "Diabetes mellitus"
    ),
    (
        "A 60-year-old woman presents with progressive memory loss and confusion over 2 years. Her MRI shows diffuse cortical atrophy especially in the temporal lobes. What is the most likely diagnosis?",
        "Alzheimer's disease"
    ),
    (
        "A 55-year-old man presents with sudden left-sided chest pain radiating to his left arm, diaphoresis, and shortness of breath for 30 minutes. ECG shows ST elevation in leads I and aVL. What is the diagnosis?",
        "Myocardial infarction"
    ),
    (
        "A 24-year-old woman presents with episodic shortness of breath, chest tightness, and wheezing that worsens in spring. Spirometry shows reversible airway obstruction. What is the most likely diagnosis?",
        "Asthma"
    ),
]

correct = 0
print("\n🔍 MODEL TEST RESULTS\n" + "="*60)

for i, (question, expected) in enumerate(test_cases, 1):
    output = generate_answer(question)
    print(f"\nQ{i}: {question}")
    print(f"Expected : {expected}")
    print(f"Model    : {output}")

    if expected.lower() in output.lower():
        print("✅ Correct")
        correct += 1
    else:
        print("❌ Incorrect")

print("\n" + "="*60)
print(f"Final Score: {correct}/{len(test_cases)}")

if correct >= 4:
    print("🔥 Strong model")
elif correct >= 3:
    print("👍 Good model")
elif correct >= 2:
    print("⚠️ Needs improvement")
else:
    print("❌ Weak model — needs more training")

🔍 MODEL TEST RESULTS
============================================================

Q1: A 21-year-old college student is brought to the emergency department with a 10-hour history of increasing headache, stiff neck, and sensitivity to light. Temperature is 39.5°C, heart rate is 110/min. What is the most likely diagnosis?
Expected : Meningitis
Model    : The answer is Cerebral hemorrhage.
❌ Incorrect

Q2: A 45-year-old man presents with polyuria, polydipsia, and a 10 kg weight loss over 2 months. His fasting blood glucose is 320 mg/dL and HbA1c is 11%. What is the diagnosis?
Expected : Diabetes mellitus
Model    : The answer is Type II diabetes mellitus (TIDM).
✅ Correct

Q3: A 60-year-old woman presents with progressive memory loss and confusion over 2 years. Her MRI shows diffuse cortical atrophy especially in the temporal lobes. What is the most likely diagnosis?
Expected : Alzheimer's disease
Model    : The answer is Alzheimer's disease.
✅ Correct

Q4: A 55-year-old man presents with sudden left-sided chest pain radiating to his left arm, diaphoresis, and shortness of breath for 30 minutes. ECG shows ST elevation in leads I and aVL. What is the diagnosis?
Expected : Myocardial infarction
Model    : The answer is Myocardial infarction (MI).
✅ Correct

Q5: A 24-year-old woman presents with episodic shortness of breath, chest tightness, and wheezing that worsens in spring. Spirometry shows reversible airway obstruction. What is the most likely diagnosis?
Expected : Asthma
Model    : The answer is Pulmonary fibrosis.
❌ Incorrect

============================================================
Final Score: 3/5
👍 Good model

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel
from huggingface_hub import login

# ✅ Config
MODEL_ID   = 'deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B'
CHECKPOINT = '/content/checkpoints_v2/checkpoint-200'
REPO_ID    = 'Hemachandiran/medqa-deepseek_v1'

# ✅ Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tokenizer.pad_token    = tokenizer.eos_token
tokenizer.padding_side = 'right'

# ✅ Load base model
base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype=torch.float16,
    device_map='auto',
    trust_remote_code=True,
)

# ✅ Load LoRA checkpoint
lora_model = PeftModel.from_pretrained(base_model, CHECKPOINT)
print('✅ Checkpoint loaded!')

# ✅ Merge LoRA into base model
merged_model = lora_model.merge_and_unload()
print('✅ LoRA merged!')

# ✅ Login and push
login(token="")

merged_model.push_to_hub(REPO_ID)
tokenizer.push_to_hub(REPO_ID)
print(f'✅ Pushed to https://huggingface.co/{REPO_ID}')

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

✅ Checkpoint loaded!
✅ LoRA merged!

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...j4arghn/model.safetensors:   2%|1         | 56.0MB / 3.55GB

README.md: 0.00B [00:00, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mp7lywvpxi/tokenizer.json: 100%|##########| 11.4MB / 11.4MB

✅ Pushed to https://huggingface.co/Hemachandiran/medqa-deepseek_v1

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model = AutoModelForCausalLM.from_pretrained(
    'Hemachandiran/medqa-deepseek_v1',
    dtype=torch.float16,
    device_map='auto',
)
tokenizer = AutoTokenizer.from_pretrained('Hemachandiran/medqa-deepseek_v1')
print('✅ Loaded from Hub!')

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/3.55G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/180 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/367 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

✅ Loaded from Hub!

In [ ]:
def ask(question):
    prompt = (
        "<|system|>\n"
        "You are a medical AI assistant trained on clinical questions. "
        "Answer clearly, accurately, and concisely.\n\n"
        f"<|user|>\n{question}\n\n"
        "<|assistant|>\n"
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    input_length = inputs["input_ids"].shape[1]

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            temperature=0.1,
            top_p=0.85,
            do_sample=True,
            repetition_penalty=1.3,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    new_tokens = outputs[0][input_length:]
    return tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

In [ ]:
question = """A 55-year-old man presents with sudden left-sided chest pain
radiating to his left arm, diaphoresis, and shortness of breath for 30 minutes.
ECG shows ST elevation in leads I and aVL. What is the diagnosis?"""

answer = ask(question)
print(f"Question: {question}")
print(f"Answer  : {answer}")

Question: A 55-year-old man presents with sudden left-sided chest pain
radiating to his left arm, diaphoresis, and shortness of breath for 30 minutes.
ECG shows ST elevation in leads I and aVL. What is the diagnosis?
Answer  : The answer is Myocardial infarction (MI).